apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-ingress.yaml
  - prometheus-ingress.yaml
  - alert-memory.yaml
  - servicemonitor-cert-manager.yaml
  - dashboards/app-dashboard.yaml
  - dashboards/infra-dashboard.yaml
  - dashboards/logs-dashboard.yaml
  - dashboards/capacity-dashboard.yaml
  - dashboards/ingress-dashboard.yaml
  - dashboards/certificates-dashboard.yaml