apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredresources
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredResources
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredresources

        violation[{"msg": msg}] {
          container := input_containers[_]
          not container.resources.requests.cpu
          msg := sprintf("container <%v> is missing resources.requests.cpu", [container.name])
        }

        violation[{"msg": msg}] {
          container := input_containers[_]
          not container.resources.requests.memory
          msg := sprintf("container <%v> is missing resources.requests.memory", [container.name])
        }

        violation[{"msg": msg}] {
          container := input_containers[_]
          not container.resources.limits.cpu
          msg := sprintf("container <%v> is missing resources.limits.cpu", [container.name])
        }

        violation[{"msg": msg}] {
          container := input_containers[_]
          not container.resources.limits.memory
          msg := sprintf("container <%v> is missing resources.limits.memory", [container.name])
        }

        input_containers[container] {
          input.review.kind.kind == "Pod"
          container := input.review.object.spec.containers[_]
        }

        input_containers[container] {
          input.review.kind.kind == "Pod"
          container := input.review.object.spec.initContainers[_]
        }

        input_containers[container] {
          workload_kinds[input.review.kind.kind]
          container := input.review.object.spec.template.spec.containers[_]
        }

        input_containers[container] {
          workload_kinds[input.review.kind.kind]
          container := input.review.object.spec.template.spec.initContainers[_]
        }

        input_containers[container] {
          input.review.kind.kind == "CronJob"
          container := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
        }

        input_containers[container] {
          input.review.kind.kind == "CronJob"
          container := input.review.object.spec.jobTemplate.spec.template.spec.initContainers[_]
        }

        workload_kinds := {"Deployment", "ReplicaSet", "StatefulSet", "DaemonSet", "Job"}
